DROP DATABASE IF EXISTS blog;
CREATE DATABASE blog;

USE blog;

DROP TABLE IF EXISTS usr;
CREATE TABLE usr(
	id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    pword VARCHAR(255) NOT NULL
);